services:

  # envoy, configured as with envoy.yaml to use extprocs
  envoy:
    image: envoyproxy/envoy:${ENVOY_VERSION:-v1.26-latest}
    ports:
      - "8080:8000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    # turn on logging as needed; can be _very_ noisy otherwise esp. with trace
    logging:
      driver: none

  # upstream "echo" server
  upstream:
    hostname: upstream
    image: echo-server
    build:
      context: _mocks/echo
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - LOG_LEVEL=info

  # extprocs
  noop:
    image: ghcr.io/wrossmorrow/envoy-extproc-sdk-java:${IMAGE_TAG:-local}
    command:
      - -Dextproc.logs.phases=true
      - -Dextproc.upstream.headers.duration=true
      - -Dextproc.downstream.headers.duration=true
      - -Dextproc.class=com.github.wrossmorrow.extproc.processors.NoOpRequestProcessor
      - -jar
      - /extproc/extproc.jar
    restart: always
  trivial:
    image: ghcr.io/wrossmorrow/envoy-extproc-sdk-java:${IMAGE_TAG:-local}
    command:
      - -Dextproc.logs.phases=true
      - -Dextproc.upstream.headers.duration=true
      - -Dextproc.downstream.headers.duration=true
      - -Dextproc.class=com.github.wrossmorrow.extproc.processors.TrivialRequestProcessor
      - -jar
      - /extproc/extproc.jar
    restart: always
  timer:
    image: ghcr.io/wrossmorrow/envoy-extproc-sdk-java:${IMAGE_TAG:-local}
    command:
      - -Dextproc.logs.phases=true
      - -Dextproc.upstream.headers.duration=true
      - -Dextproc.downstream.headers.duration=true
      - -Dextproc.class=com.github.wrossmorrow.extproc.processors.TimerRequestProcessor
      - -jar
      - /extproc/extproc.jar
    restart: always
  digest:
    image: ghcr.io/wrossmorrow/envoy-extproc-sdk-java:${IMAGE_TAG:-local}
    command:
      - -Dextproc.logs.phases=true
      - -Dextproc.upstream.headers.duration=true
      - -Dextproc.downstream.headers.duration=true
      - -Dextproc.class=com.github.wrossmorrow.extproc.processors.DigestRequestProcessor
      - -jar
      - /extproc/extproc.jar
    restart: always
  dedup:
    image: ghcr.io/wrossmorrow/envoy-extproc-sdk-java:${IMAGE_TAG:-local}
    command:
      - -Dextproc.logs.phases=true
      - -Dextproc.upstream.headers.duration=true
      - -Dextproc.downstream.headers.duration=true
      - -Dextproc.class=com.github.wrossmorrow.extproc.processors.DedupRequestProcessor
      - -jar
      - /extproc/extproc.jar
    restart: always
  # masker:
  #   image: envoy-extproc-sdk-java:
  #   command:
  #     - /extproc
  #     - masker
  echo:
    image: ghcr.io/wrossmorrow/envoy-extproc-sdk-java:${IMAGE_TAG:-local}
    command:
      - -Dextproc.logs.phases=true
      - -Dextproc.upstream.headers.duration=true
      - -Dextproc.downstream.headers.duration=true
      - -Dextproc.class=com.github.wrossmorrow.extproc.processors.EchoRequestProcessor
      - -jar
      - /extproc/extproc.jar
    restart: always
